Linux port of shader compiler (dsc-spirv).
GaijinEntertainment/DagorEngine pull request #14
Opened 2023-11-05 07:15 UTC by seanballais

**NOTE**: This PR is not yet ready for merging. I only created this PR to allow myself and others to track my porting efforts of the shader compiler as well as provide Gaijin and other interested parties avenues for feedback. Consider all commits as unstable.

Task:
- [ ] Create build scripts for Linux.<sup>1</sup>
- [ ] Port shader compiler (`dsc-spirv`).
- [ ] ~~Offer ham and cheese to basement guy.~~
- [ ] Obtain approval from Gaijin.

---

- <sup>1</sup> Most of the build scripts are Windows-oriented. In order for me to not break the pre-existing scripts and since many cannot really run in Linux natively, I opted to create Linux-oriented scripts.

2023-11-21 16:17 UTC, romasandu-gaijin requested changes

2023-11-21 16:17 UTC, romasandu-gaijin commented on prog/dagorInclude/util/dag_bindump_ext.h
> +    eastl::string::operator=(eastl::move(other));
C strings don't support move semantics. Remove this overload, `operator=(const char *other)` should be enough.

2023-11-21 16:17 UTC, romasandu-gaijin commented on prog/dagorInclude/util/dag_bindump_ext.h
> +    eastl::string::operator=(other);
Maybe try to do `using eastl::string::operator=;` instead of implementing it manually? Not sure whether GCC will like that, but worth a shot.

2023-11-21 16:35 UTC, seanballais commented
Thanks for the valuable feedback, @romasandu-gaijin! I really appreciate it. I'll get back to those this week once I am able to.

2023-12-01 07:41 UTC, NicSavichev commented
> **NOTE**: This PR is not yet ready for merging. I only created this PR to allow myself and others to track my porting efforts of 

I've updated code in our repo to alternatively compile dsc2-spriv-dev (though some changes may be the same as you have done), I expect working compiler included in next sync to DagorEngine.
I will reuse parts of your scripts that download and build DXC (needed for both linux64 and macOS), thanks for good job!

2023-12-01 10:57 UTC, NicSavichev commented
> Should we close this PR since you're working on `dsc2-spirv-dev`?

Let's close it after DagorEngine repo updated and we ensure that shader compiler is compilable and usable under linux

2024-01-02 20:06 UTC, NicSavichev commented
I've finally published release where shader compiler (along with dabuild and other utilities) are buildable for linux (and macOS)

2024-01-02 20:06 UTC, closed without merging

2024-01-04 12:09 UTC, seanballais commented
Hey, @NicSavichev! That's great news. I'll try compiling those utilities in my Linux machine if I have time to help make sure they're running smoothly. Might submit some fixes if there are any issues (especially since I'm running Pop!_OS). In any case, great job! 🥳